[package]
name = "interstellar-http-client"
version = "0.5.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
log = { workspace = true }
base64 = { workspace = true, features = ["alloc"] }
bytes = { workspace = true }
# https://github.com/tokio-rs/prost#using-prost-in-a-no_std-crate
prost = { workspace = true, features = ["prost-derive"], optional = true }
serde = { workspace = true }
serde_json = { workspace = true, features = ["alloc"] }
hex = { workspace = true, features = ["alloc"] }
# should probably be kept in sync with https://github.com/integritee-network/worker/blob/0a401bcaabb27ba4e5f59357b0a324c311b39ecd/sidechain/storage/Cargo.toml#L9
snafu = { workspace = true }
cfg-if = { workspace = true }

# SHOULD roughly match https://github.com/integritee-network/integritee-node/blob/d2262b582b2c32de68afcdf0765392d4c781e3ef/Cargo.toml#L90
parity-scale-codec = { workspace = true }
sp-io = { workspace = true, optional = true }
sp-runtime = { workspace = true, optional = true }

# when used in SGX enclave
# cf app-libs/exchange-oracle/Cargo.toml
# cf https://github.com/integritee-network/worker/blob/4083b03427890a9aeac0ddc053423b57bf590029/core/rest-client/Cargo.toml
# http_req: default is "native-tls", but that needs to (cross-)compile openssl-sys which COULD be a pain on Android; In any case, rustls works fine
http_req = { workspace = true, features = ["rust-tls"], optional = true }
http_req-sgx = { workspace = true, features = ["rust-tls", "sgx"], optional = true }

[features]
default = ["std", "with_http_req", "with_http_req_std"]
# client: SHOULD use "with_http_req_std"/"with_http_req_sgx", or not
# "with_http_req" is INTERNAL; idea from https://blog.turbo.fish/cargo-features/
# "Activating a dependency if a combination of features is active"
with_http_req = []
with_http_req_std = ["http_req"]
with_http_req_sgx = ["http_req-sgx"]
with_sp_offchain = ["sp-runtime", "sp-io"]
std = ["log/std", "hex/std", "sp-runtime?/std", "sp-io?/std", "http_req?/std"]
# core/rest-client/Cargo.toml
sgx = ["http_req-sgx?/sgx"]
