[package]
name = "tests-utils"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true, features = ["alloc"] }
rand = { workspace = true }

# cf https://github.com/rs-ipfs/rust-ipfs/blob/master/Cargo.toml
# Needed for tests/foreign_ipfs.rs
libp2p = { workspace = true, features = ["floodsub", "identify", "kad", "mplex", "noise", "ping", "yamux"] }
libp2p-identity = { workspace = true }
base64 = { workspace = true, features = ["alloc"] }
anyhow = { workspace = true }
# A recent version is required for the Send trait else
# "the trait `Send` is not implemented for `dyn Future<Output = Result<AddResponse, ipfs_api_backend_hyper::Error>>`"
# https://github.com/ferristseng/rust-ipfs-api/issues/90
# ipfs-api-backend-hyper = "0.3"
ipfs-api-backend-hyper = { workspace = true, features = ["with-send-sync", "with-builder"] }

# ipfs-api-backend-actix = { version = ">=0.7", features = [ "with-builder" ] }
# ipfs-api-prelude = { version = "*", features = [ "with-send-sync"] }
