[package]
name = "ocw-common"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
log = { version = "0.4", default-features = false }
base64 = { default-features = false, features = ["alloc"], version = "0.13" }
bytes = { version = "1.1.0", default-features = false }
# https://github.com/tokio-rs/prost#using-prost-in-a-no_std-crate
prost = { version = "0.11", default-features = false, features = ["prost-derive"] }
# "Only necessary if using Protobuf well-known types:"
# prost-types = { version = "0.11", default-features = false }

# when used via a Subtrate offchain_worker
sp-io = { optional = true, default-features = false, version = "6.0.0", git = "https://github.com/paritytech/substrate.git", branch = "polkadot-v0.9.26" }
sp-runtime = { optional = true, version = "6.0.0", default-features = false, git = "https://github.com/paritytech/substrate.git", branch = "polkadot-v0.9.26" }
sp-std = { optional = true, default-features = false, version = "4.0.0", git = "https://github.com/paritytech/substrate.git", branch = "polkadot-v0.9.26" }

# when used in SGX enclave
# cf app-libs/exchange-oracle/Cargo.toml
# TODO? git = "https://github.com/integritee-network/worker"
itc-rest-client = { optional = true, default-features = false, path = "../../core/rest-client" }
sgx_tstd = { optional = true, rev = "v1.1.3", git = "https://github.com/apache/teaclave-sgx-sdk.git"}
url = { version = "2.0.0", optional = true }
url_sgx = { package = "url", git = "https://github.com/mesalock-linux/rust-url-sgx", tag = "sgx_1.1.3", optional = true }

[features]
default = ["std"]
std = [
	"log/std",
	"sp-io/std",
	"sp-runtime/std",
	"sp-std/std",
	# TODO?
	"itc-rest-client/std",
	"url"
]
# core/rest-client/Cargo.toml
sgx = [
	"sgx_tstd",
    "itc-rest-client/sgx",
	"url_sgx",
]