name: Build and Test STD

on:
  push:

jobs:
  ##########################################################################
  ##########################################################################
  # TODO split test and lint; but that REQUIRE caching else recompile from scratch in between
  rust:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # TODO: "with_sp_offchain": requires to setup a Mock Substrate runtime so for now we skip it
        # This is not ideal, but this repo is tested as part of the others(mostly "pallets") so...
        rust_args:
          [
            { features: "with_http_req,prost", test_args: "" },
            { features: "with_http_req,with_sp_offchain", test_args: "" },
            { features: "with_sp_offchain", test_args: "-h" },
          ]
    steps:
      ##########################################################################
      # This is pretty dumb: we MUST call action/checkout BEFORE using a local action...
      # else: Error: Can't find 'action.yml', 'action.yaml' or 'Dockerfile' under '/home/runner/work/rs-common/rs-common/.github/actions/setup'. Did you forget to run actions/checkout before running your local action?
      - uses: Interstellar-Network/gh-actions/prepare@ci-v4
        with:
          interstellar_token_ci: ${{ secrets.INTERSTELLAR_TOKEN_CI }}
          install_cmake_and_ninja: false

      ##########################################################################

      - uses: Interstellar-Network/gh-actions/prepare_rust@ci-v4
        with:
          toolchain_components: "rustfmt,clippy"

      ##########################################################################

      - uses: Interstellar-Network/gh-actions/install-go-ipfs@ci-v4

      ##########################################################################

      - uses: Interstellar-Network/gh-actions/rust-build-and-test@ci-v4
        with:
          # default = --no-default-features --features=with_http_req,http_req,std
          test_args: "--features=${{ matrix.rust_args.features }} ${{ matrix.rust_args.test_args }}"

      ##########################################################################

      - uses: Interstellar-Network/gh-actions/rust-lint@ci-v4
        with:
          clippy_args: --features=${{ matrix.rust_args.features }} -- -D warnings

      ##########################################################################

      # TODO move into separate action? ideally into a JS action "post" that setup ccache?
      # NOTE: remove if using "rust-build-and-test"
      - name: Print ccache/sccache stats
        # display stats even if tests failed
        if: always()
        run: |
          ccache --show-stats || true
          sccache --show-stats || true
        shell: bash

  ##########################################################################
  ##########################################################################
  sgx:
    # Seems to be stuck on 22.04 cf https://github.com/integritee-network/integritee-dev/blob/e8f9d8d44f0ef89ffecfe796e8f9c35120f73c47/worker/Dockerfile#L21
    runs-on: ubuntu-22.04
    steps:
      ##########################################################################
      # This is pretty dumb: we MUST call action/checkout BEFORE using a local action...
      # else: Error: Can't find 'action.yml', 'action.yaml' or 'Dockerfile' under '/home/runner/work/rs-common/rs-common/.github/actions/setup'. Did you forget to run actions/checkout before running your local action?
      - uses: Interstellar-Network/gh-actions/prepare@ci-v4
        with:
          interstellar_token_ci: ${{ secrets.INTERSTELLAR_TOKEN_CI }}
          install_cmake_and_ninja: false

      ##########################################################################

      - uses: Interstellar-Network/gh-actions/prepare_rust@ci-v4
        with:
          use_toolchain_toml: "true"
          toolchain_toml_path: ./tests_sgx/samplecode/project_template/enclave/rust-toolchain.toml
          toolchain_components: ""

      ##########################################################################

      - uses: Interstellar-Network/gh-actions/install-sgx-sdk@ci-v4

      # https://hub.docker.com/r/hashicorp/http-echo/
      # NOTE: apparently there is no way to pass "run" arguments to a container
      # using "service"; so we start it manually
      - name: Start HTTP echo server
        # TODO remove ccache --clear; only here to debug
        run: |
          podman run -d -p 8080:8080 hashicorp/http-echo -listen=:8080 -text="hello world"
        shell: bash

      # cf core-primitives/enclave-api/build.rs and service/build.rs
      - name: Build SGX samplecode
        # TODO remove ccache --clear; only here to debug
        run: |
          curl $HTTP_ECHO_URL -v
          echo http echo OK: $?

          cd tests_sgx
          export CUSTOM_EDL_PATH=$PWD/edl
          export CUSTOM_COMMON_PATH=$PWD/common
          (cd samplecode/project_template && make clean && make && cd bin/ && ./app)
        env:
          HTTP_ECHO_URL: "http://localhost:8080/"
        shell: bash
